export const en = {
  'hud.coins': 'Coins',
  'hud.honey': 'Honey',
  'hud.kg': '{kg} kg',
  'hud.dayYear': 'Day {day} · Year {year}',
  'hud.clock': 'Calendar and game speed',
  'hud.pause': 'Pause',
  'hud.speed': '{n}x',
  'hud.speedLabel': '{n}x speed',
  'hud.resetView': 'Reset view',
  'hud.settings': 'Settings',

  'season.spring': 'Spring',
  'season.summer': 'Summer',
  'season.autumn': 'Autumn',
  'season.winter': 'Winter',

  'toolbar.label': 'Actions',
  'toolbar.shop': 'Shop',
  'toolbar.market': 'Market',
  'toolbar.harvestAll': 'Harvest All',

  'panel.close': 'Close',

  'shop.title': 'Shop',
  'shop.hint': 'Pick something, then click a tile to place it. Right-click or Esc to stop.',
  'shop.cost': '{coins}',

  'market.title': 'Market',
  'market.have': 'You have {kg} kg',
  'market.price': '{price} coins per kg',
  'market.less': 'Less',
  'market.more': 'More',
  'market.sell': 'Sell {kg} kg',
  'market.sellAll': 'Sell all',
  'market.preview': '= {coins} coins',
  'market.nothing': 'Nothing to sell yet. Harvest some honey first.',

  'def.hive': 'Beehive',
  'def.bed_wildflower': 'Wildflower bed',
  'def.house': 'Beekeeper’s house',
  'defDesc.hive': 'Turns nectar from beds next to it into honey.',
  'defDesc.bed_wildflower': 'Makes nectar for the hives next to it.',
  'defDesc.house': 'Home sweet home.',

  'resource.coins': 'Coins',
  'resource.honey_wildflower': 'Wildflower honey',

  'inspect.label': 'Details',
  'inspect.fill': '{have} / {cap} kg',
  'inspect.rate': '{rate} kg/day',
  'inspect.sources': '{count} flower beds in range',
  'inspect.shared': '{n} shared with another hive',
  'inspect.yield': '{n} nectar/day',
  'inspect.feedsNone': 'No hive next to it: its nectar is wasted',
  'inspect.feedsOne': 'Feeds 1 hive',
  'inspect.feedsMany': 'Shared by {n} hives',
  'inspect.harvest': 'Harvest',
  'inspect.remove': 'Remove (+{coins})',
  'inspect.confirm': 'Confirm remove',

  'hint.place': '{name} · {coins} coins',

  'toast.harvested': '+{kg} kg',
  'toast.sold': '+{coins} coins',
  'toast.full': 'A hive is full. Time to harvest!',
  'toast.safetyNet': 'The village lends you {coins} coins to get going again.',

  'reason.unknown_def': 'Unknown item',
  'reason.not_purchasable': 'That isn’t for sale',
  'reason.out_of_bounds': 'Outside the map',
  'reason.not_owned': 'You don’t own this land yet',
  'reason.tile_occupied': 'Something is already here',
  'reason.tile_not_buildable': 'Can’t build on this tile',
  'reason.insufficient_funds': 'Not enough coins',
  'reason.unknown_entity': 'That’s no longer here',
  'reason.not_removable': 'This can’t be removed',
  'reason.last_producer': 'You need at least one hive',
  'reason.nothing_to_harvest': 'Nothing to harvest yet',
  'reason.invalid_amount': 'Pick an amount first',
  'reason.insufficient_resource': 'You don’t have that much',
  'reason.not_sellable': 'The market doesn’t buy that',
  'reason.invalid_speed': 'Unknown speed',
  'reason.internal_error': 'Something went wrong',

  'settings.reset': 'Reset save',
  'settings.resetConfirm': 'Start over? Your current game will be deleted.',

  'notice.noSave': 'Progress won’t be saved in this browser.',
  'notice.corruptSave': 'Couldn’t load your save, so a new game was started.',

  'fatal.noWebglTitle': 'Your browser can’t show this game',
  'fatal.noWebglBody': 'It needs WebGL 2. Try an up-to-date Chrome, Firefox, Safari or Edge.',
  'fatal.contextLost': 'Graphics reset…',
  'fatal.reload': 'Reload',
} as const;
